/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedListagemServicosRouteImport } from './routes/_authenticated.listagem-servicos'
import { Route as AuthenticatedListagemLojasRouteImport } from './routes/_authenticated.listagem-lojas'
import { Route as AuthenticatedListagemFuncionariosRouteImport } from './routes/_authenticated.listagem-funcionarios'
import { Route as AuthenticatedListagemEquipesRouteImport } from './routes/_authenticated.listagem-equipes'
import { Route as AuthenticatedListagemCobrancistasRouteImport } from './routes/_authenticated.listagem-cobrancistas'
import { Route as AuthenticatedListagemClientesRouteImport } from './routes/_authenticated.listagem-clientes'
import { Route as AuthenticatedListagemAreasFuncionarioRouteImport } from './routes/_authenticated.listagem-areas-funcionario'
import { Route as AuthenticatedListagemAreasAtuacaoRouteImport } from './routes/_authenticated.listagem-areas-atuacao'
import { Route as AuthenticatedCadastroServicoRouteImport } from './routes/_authenticated.cadastro-servico'
import { Route as AuthenticatedCadastroLojaRouteImport } from './routes/_authenticated.cadastro-loja'
import { Route as AuthenticatedCadastroFuncionarioRouteImport } from './routes/_authenticated.cadastro-funcionario'
import { Route as AuthenticatedCadastroEquipeRouteImport } from './routes/_authenticated.cadastro-equipe'
import { Route as AuthenticatedCadastroCobrancistaRouteImport } from './routes/_authenticated.cadastro-cobrancista'
import { Route as AuthenticatedCadastroClienteRouteImport } from './routes/_authenticated.cadastro-cliente'
import { Route as AuthenticatedCadastroAreaFuncionarioRouteImport } from './routes/_authenticated.cadastro-area-funcionario'
import { Route as AuthenticatedCadastroAreaAtuacaoRouteImport } from './routes/_authenticated.cadastro-area-atuacao'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListagemServicosRoute =
  AuthenticatedListagemServicosRouteImport.update({
    id: '/listagem-servicos',
    path: '/listagem-servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemLojasRoute =
  AuthenticatedListagemLojasRouteImport.update({
    id: '/listagem-lojas',
    path: '/listagem-lojas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemFuncionariosRoute =
  AuthenticatedListagemFuncionariosRouteImport.update({
    id: '/listagem-funcionarios',
    path: '/listagem-funcionarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemEquipesRoute =
  AuthenticatedListagemEquipesRouteImport.update({
    id: '/listagem-equipes',
    path: '/listagem-equipes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemCobrancistasRoute =
  AuthenticatedListagemCobrancistasRouteImport.update({
    id: '/listagem-cobrancistas',
    path: '/listagem-cobrancistas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemClientesRoute =
  AuthenticatedListagemClientesRouteImport.update({
    id: '/listagem-clientes',
    path: '/listagem-clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemAreasFuncionarioRoute =
  AuthenticatedListagemAreasFuncionarioRouteImport.update({
    id: '/listagem-areas-funcionario',
    path: '/listagem-areas-funcionario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListagemAreasAtuacaoRoute =
  AuthenticatedListagemAreasAtuacaoRouteImport.update({
    id: '/listagem-areas-atuacao',
    path: '/listagem-areas-atuacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroServicoRoute =
  AuthenticatedCadastroServicoRouteImport.update({
    id: '/cadastro-servico',
    path: '/cadastro-servico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroLojaRoute =
  AuthenticatedCadastroLojaRouteImport.update({
    id: '/cadastro-loja',
    path: '/cadastro-loja',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroFuncionarioRoute =
  AuthenticatedCadastroFuncionarioRouteImport.update({
    id: '/cadastro-funcionario',
    path: '/cadastro-funcionario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroEquipeRoute =
  AuthenticatedCadastroEquipeRouteImport.update({
    id: '/cadastro-equipe',
    path: '/cadastro-equipe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroCobrancistaRoute =
  AuthenticatedCadastroCobrancistaRouteImport.update({
    id: '/cadastro-cobrancista',
    path: '/cadastro-cobrancista',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroClienteRoute =
  AuthenticatedCadastroClienteRouteImport.update({
    id: '/cadastro-cliente',
    path: '/cadastro-cliente',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroAreaFuncionarioRoute =
  AuthenticatedCadastroAreaFuncionarioRouteImport.update({
    id: '/cadastro-area-funcionario',
    path: '/cadastro-area-funcionario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroAreaAtuacaoRoute =
  AuthenticatedCadastroAreaAtuacaoRouteImport.update({
    id: '/cadastro-area-atuacao',
    path: '/cadastro-area-atuacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cadastro-area-atuacao': typeof AuthenticatedCadastroAreaAtuacaoRoute
  '/cadastro-area-funcionario': typeof AuthenticatedCadastroAreaFuncionarioRoute
  '/cadastro-cliente': typeof AuthenticatedCadastroClienteRoute
  '/cadastro-cobrancista': typeof AuthenticatedCadastroCobrancistaRoute
  '/cadastro-equipe': typeof AuthenticatedCadastroEquipeRoute
  '/cadastro-funcionario': typeof AuthenticatedCadastroFuncionarioRoute
  '/cadastro-loja': typeof AuthenticatedCadastroLojaRoute
  '/cadastro-servico': typeof AuthenticatedCadastroServicoRoute
  '/listagem-areas-atuacao': typeof AuthenticatedListagemAreasAtuacaoRoute
  '/listagem-areas-funcionario': typeof AuthenticatedListagemAreasFuncionarioRoute
  '/listagem-clientes': typeof AuthenticatedListagemClientesRoute
  '/listagem-cobrancistas': typeof AuthenticatedListagemCobrancistasRoute
  '/listagem-equipes': typeof AuthenticatedListagemEquipesRoute
  '/listagem-funcionarios': typeof AuthenticatedListagemFuncionariosRoute
  '/listagem-lojas': typeof AuthenticatedListagemLojasRoute
  '/listagem-servicos': typeof AuthenticatedListagemServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cadastro-area-atuacao': typeof AuthenticatedCadastroAreaAtuacaoRoute
  '/cadastro-area-funcionario': typeof AuthenticatedCadastroAreaFuncionarioRoute
  '/cadastro-cliente': typeof AuthenticatedCadastroClienteRoute
  '/cadastro-cobrancista': typeof AuthenticatedCadastroCobrancistaRoute
  '/cadastro-equipe': typeof AuthenticatedCadastroEquipeRoute
  '/cadastro-funcionario': typeof AuthenticatedCadastroFuncionarioRoute
  '/cadastro-loja': typeof AuthenticatedCadastroLojaRoute
  '/cadastro-servico': typeof AuthenticatedCadastroServicoRoute
  '/listagem-areas-atuacao': typeof AuthenticatedListagemAreasAtuacaoRoute
  '/listagem-areas-funcionario': typeof AuthenticatedListagemAreasFuncionarioRoute
  '/listagem-clientes': typeof AuthenticatedListagemClientesRoute
  '/listagem-cobrancistas': typeof AuthenticatedListagemCobrancistasRoute
  '/listagem-equipes': typeof AuthenticatedListagemEquipesRoute
  '/listagem-funcionarios': typeof AuthenticatedListagemFuncionariosRoute
  '/listagem-lojas': typeof AuthenticatedListagemLojasRoute
  '/listagem-servicos': typeof AuthenticatedListagemServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/cadastro-area-atuacao': typeof AuthenticatedCadastroAreaAtuacaoRoute
  '/_authenticated/cadastro-area-funcionario': typeof AuthenticatedCadastroAreaFuncionarioRoute
  '/_authenticated/cadastro-cliente': typeof AuthenticatedCadastroClienteRoute
  '/_authenticated/cadastro-cobrancista': typeof AuthenticatedCadastroCobrancistaRoute
  '/_authenticated/cadastro-equipe': typeof AuthenticatedCadastroEquipeRoute
  '/_authenticated/cadastro-funcionario': typeof AuthenticatedCadastroFuncionarioRoute
  '/_authenticated/cadastro-loja': typeof AuthenticatedCadastroLojaRoute
  '/_authenticated/cadastro-servico': typeof AuthenticatedCadastroServicoRoute
  '/_authenticated/listagem-areas-atuacao': typeof AuthenticatedListagemAreasAtuacaoRoute
  '/_authenticated/listagem-areas-funcionario': typeof AuthenticatedListagemAreasFuncionarioRoute
  '/_authenticated/listagem-clientes': typeof AuthenticatedListagemClientesRoute
  '/_authenticated/listagem-cobrancistas': typeof AuthenticatedListagemCobrancistasRoute
  '/_authenticated/listagem-equipes': typeof AuthenticatedListagemEquipesRoute
  '/_authenticated/listagem-funcionarios': typeof AuthenticatedListagemFuncionariosRoute
  '/_authenticated/listagem-lojas': typeof AuthenticatedListagemLojasRoute
  '/_authenticated/listagem-servicos': typeof AuthenticatedListagemServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/home'
    | '/login'
    | '/register'
    | '/cadastro-area-atuacao'
    | '/cadastro-area-funcionario'
    | '/cadastro-cliente'
    | '/cadastro-cobrancista'
    | '/cadastro-equipe'
    | '/cadastro-funcionario'
    | '/cadastro-loja'
    | '/cadastro-servico'
    | '/listagem-areas-atuacao'
    | '/listagem-areas-funcionario'
    | '/listagem-clientes'
    | '/listagem-cobrancistas'
    | '/listagem-equipes'
    | '/listagem-funcionarios'
    | '/listagem-lojas'
    | '/listagem-servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/home'
    | '/login'
    | '/register'
    | '/cadastro-area-atuacao'
    | '/cadastro-area-funcionario'
    | '/cadastro-cliente'
    | '/cadastro-cobrancista'
    | '/cadastro-equipe'
    | '/cadastro-funcionario'
    | '/cadastro-loja'
    | '/cadastro-servico'
    | '/listagem-areas-atuacao'
    | '/listagem-areas-funcionario'
    | '/listagem-clientes'
    | '/listagem-cobrancistas'
    | '/listagem-equipes'
    | '/listagem-funcionarios'
    | '/listagem-lojas'
    | '/listagem-servicos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/home'
    | '/login'
    | '/register'
    | '/_authenticated/cadastro-area-atuacao'
    | '/_authenticated/cadastro-area-funcionario'
    | '/_authenticated/cadastro-cliente'
    | '/_authenticated/cadastro-cobrancista'
    | '/_authenticated/cadastro-equipe'
    | '/_authenticated/cadastro-funcionario'
    | '/_authenticated/cadastro-loja'
    | '/_authenticated/cadastro-servico'
    | '/_authenticated/listagem-areas-atuacao'
    | '/_authenticated/listagem-areas-funcionario'
    | '/_authenticated/listagem-clientes'
    | '/_authenticated/listagem-cobrancistas'
    | '/_authenticated/listagem-equipes'
    | '/_authenticated/listagem-funcionarios'
    | '/_authenticated/listagem-lojas'
    | '/_authenticated/listagem-servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/listagem-servicos': {
      id: '/_authenticated/listagem-servicos'
      path: '/listagem-servicos'
      fullPath: '/listagem-servicos'
      preLoaderRoute: typeof AuthenticatedListagemServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-lojas': {
      id: '/_authenticated/listagem-lojas'
      path: '/listagem-lojas'
      fullPath: '/listagem-lojas'
      preLoaderRoute: typeof AuthenticatedListagemLojasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-funcionarios': {
      id: '/_authenticated/listagem-funcionarios'
      path: '/listagem-funcionarios'
      fullPath: '/listagem-funcionarios'
      preLoaderRoute: typeof AuthenticatedListagemFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-equipes': {
      id: '/_authenticated/listagem-equipes'
      path: '/listagem-equipes'
      fullPath: '/listagem-equipes'
      preLoaderRoute: typeof AuthenticatedListagemEquipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-cobrancistas': {
      id: '/_authenticated/listagem-cobrancistas'
      path: '/listagem-cobrancistas'
      fullPath: '/listagem-cobrancistas'
      preLoaderRoute: typeof AuthenticatedListagemCobrancistasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-clientes': {
      id: '/_authenticated/listagem-clientes'
      path: '/listagem-clientes'
      fullPath: '/listagem-clientes'
      preLoaderRoute: typeof AuthenticatedListagemClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-areas-funcionario': {
      id: '/_authenticated/listagem-areas-funcionario'
      path: '/listagem-areas-funcionario'
      fullPath: '/listagem-areas-funcionario'
      preLoaderRoute: typeof AuthenticatedListagemAreasFuncionarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listagem-areas-atuacao': {
      id: '/_authenticated/listagem-areas-atuacao'
      path: '/listagem-areas-atuacao'
      fullPath: '/listagem-areas-atuacao'
      preLoaderRoute: typeof AuthenticatedListagemAreasAtuacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-servico': {
      id: '/_authenticated/cadastro-servico'
      path: '/cadastro-servico'
      fullPath: '/cadastro-servico'
      preLoaderRoute: typeof AuthenticatedCadastroServicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-loja': {
      id: '/_authenticated/cadastro-loja'
      path: '/cadastro-loja'
      fullPath: '/cadastro-loja'
      preLoaderRoute: typeof AuthenticatedCadastroLojaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-funcionario': {
      id: '/_authenticated/cadastro-funcionario'
      path: '/cadastro-funcionario'
      fullPath: '/cadastro-funcionario'
      preLoaderRoute: typeof AuthenticatedCadastroFuncionarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-equipe': {
      id: '/_authenticated/cadastro-equipe'
      path: '/cadastro-equipe'
      fullPath: '/cadastro-equipe'
      preLoaderRoute: typeof AuthenticatedCadastroEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-cobrancista': {
      id: '/_authenticated/cadastro-cobrancista'
      path: '/cadastro-cobrancista'
      fullPath: '/cadastro-cobrancista'
      preLoaderRoute: typeof AuthenticatedCadastroCobrancistaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-cliente': {
      id: '/_authenticated/cadastro-cliente'
      path: '/cadastro-cliente'
      fullPath: '/cadastro-cliente'
      preLoaderRoute: typeof AuthenticatedCadastroClienteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-area-funcionario': {
      id: '/_authenticated/cadastro-area-funcionario'
      path: '/cadastro-area-funcionario'
      fullPath: '/cadastro-area-funcionario'
      preLoaderRoute: typeof AuthenticatedCadastroAreaFuncionarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-area-atuacao': {
      id: '/_authenticated/cadastro-area-atuacao'
      path: '/cadastro-area-atuacao'
      fullPath: '/cadastro-area-atuacao'
      preLoaderRoute: typeof AuthenticatedCadastroAreaAtuacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCadastroAreaAtuacaoRoute: typeof AuthenticatedCadastroAreaAtuacaoRoute
  AuthenticatedCadastroAreaFuncionarioRoute: typeof AuthenticatedCadastroAreaFuncionarioRoute
  AuthenticatedCadastroClienteRoute: typeof AuthenticatedCadastroClienteRoute
  AuthenticatedCadastroCobrancistaRoute: typeof AuthenticatedCadastroCobrancistaRoute
  AuthenticatedCadastroEquipeRoute: typeof AuthenticatedCadastroEquipeRoute
  AuthenticatedCadastroFuncionarioRoute: typeof AuthenticatedCadastroFuncionarioRoute
  AuthenticatedCadastroLojaRoute: typeof AuthenticatedCadastroLojaRoute
  AuthenticatedCadastroServicoRoute: typeof AuthenticatedCadastroServicoRoute
  AuthenticatedListagemAreasAtuacaoRoute: typeof AuthenticatedListagemAreasAtuacaoRoute
  AuthenticatedListagemAreasFuncionarioRoute: typeof AuthenticatedListagemAreasFuncionarioRoute
  AuthenticatedListagemClientesRoute: typeof AuthenticatedListagemClientesRoute
  AuthenticatedListagemCobrancistasRoute: typeof AuthenticatedListagemCobrancistasRoute
  AuthenticatedListagemEquipesRoute: typeof AuthenticatedListagemEquipesRoute
  AuthenticatedListagemFuncionariosRoute: typeof AuthenticatedListagemFuncionariosRoute
  AuthenticatedListagemLojasRoute: typeof AuthenticatedListagemLojasRoute
  AuthenticatedListagemServicosRoute: typeof AuthenticatedListagemServicosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCadastroAreaAtuacaoRoute: AuthenticatedCadastroAreaAtuacaoRoute,
  AuthenticatedCadastroAreaFuncionarioRoute:
    AuthenticatedCadastroAreaFuncionarioRoute,
  AuthenticatedCadastroClienteRoute: AuthenticatedCadastroClienteRoute,
  AuthenticatedCadastroCobrancistaRoute: AuthenticatedCadastroCobrancistaRoute,
  AuthenticatedCadastroEquipeRoute: AuthenticatedCadastroEquipeRoute,
  AuthenticatedCadastroFuncionarioRoute: AuthenticatedCadastroFuncionarioRoute,
  AuthenticatedCadastroLojaRoute: AuthenticatedCadastroLojaRoute,
  AuthenticatedCadastroServicoRoute: AuthenticatedCadastroServicoRoute,
  AuthenticatedListagemAreasAtuacaoRoute:
    AuthenticatedListagemAreasAtuacaoRoute,
  AuthenticatedListagemAreasFuncionarioRoute:
    AuthenticatedListagemAreasFuncionarioRoute,
  AuthenticatedListagemClientesRoute: AuthenticatedListagemClientesRoute,
  AuthenticatedListagemCobrancistasRoute:
    AuthenticatedListagemCobrancistasRoute,
  AuthenticatedListagemEquipesRoute: AuthenticatedListagemEquipesRoute,
  AuthenticatedListagemFuncionariosRoute:
    AuthenticatedListagemFuncionariosRoute,
  AuthenticatedListagemLojasRoute: AuthenticatedListagemLojasRoute,
  AuthenticatedListagemServicosRoute: AuthenticatedListagemServicosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgendaRoute: AgendaRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
